[package]
name = "init_core"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "*"
anyhow = "*"
tokio = { version = "*", features = ["process", "rt", "macros", "fs"] }
toml = "*"
serde = { version = "*", features = ["derive"] }
os_info = "*"
