[meta]
version = "1.1"

# APP 1: Firefox
[[apps]]
id = "firefox"
name = "Mozilla Firefox"
description = "Mozilla Firefox, or simply Firefox, is a free and open-source web browser developed by the Mozilla Foundation and its subsidiary, the Mozilla Corporation. The software is available for Windows, macOS, and Linux systems."
icon = "icons/firefox.svg"

[apps.packages]
winget = "Mozilla.Firefox"
pacman = "firefox"
paru = "firefox"
apt = "firefox"

# APP 2: Visual Studio Code
[[apps]]
id = "vscode"
name = "VS Code"
description = "Visual Studio Code (commonly referred to as VS Code) is an integrated development environment developed by Microsoft for Windows, Linux, macOS and web browsers. Features include support for debugging, syntax highlighting, intelligent code completion, snippets, code refactoring, and embedded version control with Git."
icon = "icons/vscode.svg"

[apps.packages]
winget = "Microsoft.VisualStudioCode"
pacman = "code"
paru = "visual-studio-code-bin"
apt = "code"

# APP 3: VLC Media Player
[[apps]]
id = "vlc"
name = "VLC Media Player"
description = "VLC media player (previously the VideoLAN Client), sometimes abbreviated as VMP, is a free and open-source, portable, cross-platform media player software and streaming media server developed by the VideoLAN project. VLC is available for desktop operating systems and mobile platforms, such as Android, iOS and iPadOS."
icon = "icons/vlc.svg"

[apps.packages]
winget = "VideoLAN.VLC"
pacman = "vlc"
paru = "vlc"
apt = "vlc"
